# ---------------------------------------------------------------------------- #
# ---------- BUILD ----------------------------------------------------------- #
# ---------------------------------------------------------------------------- #
name: "Flow123d-{environment}-debug-build"
display-name: "{build-type} / Flow123d build"
defaults: flow123d-build
builders:
  - inject:
      properties-file: prop.file
  - shell: |
      # start image
      docker rm -f cont{environment}{build-type} || echo "container not running"
      flow123d/bin/fterm update
      flow123d/bin/fterm dbg -- \
          --privileged -di \
          --name cont{environment}{build-type} \
          --volume /home/builder/git-cache/flow123d.git:/home/builder/git-cache/flow123d.git \
          --volume ${{WORKSPACE}}/docker:/opt/flow_build    

      # delete old build
      docker exec cont{environment}{build-type} bash -c "rm -rf /opt/flow_build/{{*,.*}}" || true

      # copy config
      docker exec cont{environment}{build-type} git clone --reference /home/builder/git-cache/flow123d.git -b ${{_GIT_BRANCH}} https://github.com/flow123d/flow123d.git /opt/flow_build
      docker exec cont{environment}{build-type} cp /opt/flow_build/config/config-jenkins-docker-{build-type}.cmake /opt/flow_build/config.cmake

      # configure and compile
      docker exec cont{environment}{build-type} make -C /opt/flow_build -j4 all
      docker exec cont{environment}{build-type} make -C /opt/flow_build/build_tree/unit_tests -j4 gtest_mpi_obj
