# ---------------------------------------------------------------------------- #
# ---------- PACKAGE --------------------------------------------------------- #
# ---------------------------------------------------------------------------- #
name: "Flow123d-{platform}-{build-type}-package"
display-name: "{build-type} / Flow123d package"
defaults: flow123d-build
builders:
  - inject:
      properties-file: prop.file
  - shell: |
      destination=$(pwd)/publish

      rm -rf publish && mkdir -p publish
      rm -rf docker-config
      git clone https://github.com/flow123d/docker-config.git

      make -C docker-config/package \
              destination=$destination \
              all

      make -C docker-config/package \
              destination=$destination \
              remove-unwanted

      make -C docker-config/package \
              push-to-hub

      ls -la $destination

publishers:
  - cifs:
      site: 'flow123d.at.public'
      target: '/docker-images/${{DOCKER_IMAGE_NAME}}/'
      source: publish/**/*
      remove-prefix: publish/
