name: Flow123d debug CI

on: 
    push:
        branches: 
        - "**"
    
    workflow_dispatch:
        inputs:
            environment:
                description: Build environment [gnu, intel].
                type: choice
                options:
                    - gnu
                    - intel
                required: false
                default: gnu

env:
  autopull:  0

jobs:
    build:
        runs-on: ubuntu-latest
        name: Flow123d debug main build
     
        steps:
        - uses: actions/checkout@v3
        - name: Build flow123d, verify, tarball.
          run: config/tests/make_build_dir.sh gnu
        - uses: actions/upload-artifact@v3
          with:         
            name: build_dir
            path: build_dir.tar
    
    integration_tests:
        needs: [build]
        runs-on: ubuntu-latest
        name: Integration Test 
        continue-on-error: True
        strategy:
          matrix:
            test_dir:
            - 01_cmd_line
            - 02_generic_input
            - 03_generic_output
            - 04_generic_mesh
            - 05_tutorial
            - 06_errors
            - 10_darcy
            - 11_darcy_bc
            - 12_darcy_frac
            - 13_darcy_time
            - 14_darcy_richards
            - 20_solute_fv
            - 21_solute_fv_frac
            - 22_solute_fv_time
            - 24_solute_dg
            - 25_solute_dg_bc
            - 26_solute_dg_frac
            - 27_solute_dg_time
            - 30_sorption
            - 31_dual_por
            - 32_decay
            - 33_reaction
            - 34_sorption_dg
            - 40_heat
            - 50_mechanics
            
        steps:  
        - uses: actions/checkout@v3
        - uses: actions/download-artifact@v3
          with:
            name: build_dir
        - run: config/tests/run_with_build_dir.sh tests/runtest tests/${{matrix.test_dir}}  --keep-going --batch 
        
    unit_tests:
        needs: [build]
        runs-on: ubuntu-latest
        name: Unit Test 
        continue-on-error: True
        strategy:
          matrix:
            test_dir:
            - coupling
            - fem
            - fields
            - flow
            - input
            - intersection
            - la
            - mesh
            - output
            - scripts
            - system
            - test_scripts
            - tools
        steps:  
        - uses: actions/checkout@v3
        - uses: actions/download-artifact@v3
          with:
            name: build_dir
        - run: config/tests/run_with_build_dir.sh make -C build_tree/unit_tests/${{matrix.test_dir}} -k all-test

    build_doc:
        needs: [build]
        runs-on: ubuntu-latest
        name: Test build doc
        continue-on-error: True
        outputs:
            status: ${{job.status}}
        steps:  
        - uses: actions/checkout@v3
        - uses: actions/download-artifact@v3
          with:
            name: build_dir
        - run: config/tests/run_with_build_dir.sh make ref-doc

    conclusion:
        #needs: [integration_tests, unit_tests, build_doc]
        runs-on: ubuntu-latest
        name: Workflow conclusion from all job results 
        # continue-on-error jobs always reports sucess to the workflow
        steps:
        - run:
            #echo ${{jobs.integration_tests.outcome}}
            #echo ${{jobs.integration_tests.outputs}}
            #echo ${{jobs.unit_tests.status}}
            #echo ${{jobs.unit_tests.output}}
            echo ${{needs.build_doc.result}}
            echo ${{needs.build_doc.outputs.status}}
            #if 
            #    exit 1
            #fi
          
# steps.xyz.outcome  ... The result before continue-on-error is applied. Possible values: success, failure, cancelled, skipped.
# steps.xyz.conclusion .. The result after continue-on-error is applied. Always success for continue-on-error.
# "${{ job.status }}" ?? status of actual job 
