name: CI build, tests and alpha release of images and packages
# Build the ci-<env>:<version>_<commit> image and CI packages on SHARE/docker-images/<version>_<commit>
# Triggered on push to specified branches.

on: 
    push:
        branches:
        - master
        - JB_release_tests
        - 3.9.1
    
    # !! workflow_dispatch configuration must be in the default branch, i.e. 'master'
    # can also start manually on any branch
    workflow_dispatch:
        inputs:
            environment:
                description: Build environment [gnu, intel].
                type: choice
                options:
                    - gnu
                    - intel
                required: false
                default: gnu

                

env:
  DOCKER_USER: ${{secrets.DOCKER_HUB_FLOW123D_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_FLOW123D_TOKEN}}
  environment: gnu
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set variables
      id: vars
      run: |
        git_commit=`git rev-parse --short=6 HEAD`
        release_tag=`cat version`_${git_commit}
        echo ${release_tag}

        # can not use environment variables in github actions
        echo ::set-output name=pubdir::publish_${environment}
        echo ::set-output name=reltag::${release_tag}

    - name: Check vars
      run: |
          echo pubdir="${{ steps.vars.outputs.pubdir }}"    
          echo reltag="${{ steps.vars.outputs.reltag }}"

    - name: Build flow123d, verify, tarball.

    - name: Build packages
      run: |
        # Login for finall push to docker hub
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
        
        
        # make_packages <environment> <image_name_base> [push]
        release_tag="${{ steps.vars.outputs.reltag }}"
        #config/package/make_packages.sh ${environment} ci ${release_tag} push
        config/build/auto_build.sh rel ${environment} ci ${release_tag}  
    - uses: actions/upload-artifact@v3
      with:         
        name: build_dir
        path: build_dir.tar    

 
    packages:
        needs: [build]
        runs-on: ubuntu-latest
        name: Packages
        continue-on-error: True
        outputs:
            status: ${{job.status}}

        steps:
        - uses: actions/checkout@v3
        - uses: actions/download-artifact@v3
          with:
            name: build_dir
        - run: |
            release_tag="${{ steps.vars.outputs.reltag }}"
            make_packages.sh ${environment} ci ${release_tag} push
    
        - name: upload artifacts
          uses: actions/upload-artifact@v3
          with:       
            path: |
                ${{ steps.vars.outputs.pubdir }}/flow123d_${{ steps.vars.outputs.reltag }}_doc.pdf 
                ${{ steps.vars.outputs.pubdir }}/flow123d_${{ steps.vars.outputs.reltag }}_linux_install.json 
                ${{ steps.vars.outputs.pubdir }}/flow123d_${{ steps.vars.outputs.reltag }}_linux_install.tar.gz 
                ${{ steps.vars.outputs.pubdir }}/flow123d_${{ steps.vars.outputs.reltag }}_windows_install.exe 
                ${{ steps.vars.outputs.pubdir }}/flow123d_${{ steps.vars.outputs.reltag }}_windows_install.json 
      
        - name: SCP upload to Share
          run: |
            release_tag="${{ steps.vars.outputs.reltag }}"
            config/package/ssh_upload.sh ${{ steps.vars.outputs.pubdir }} ci-packages/${release_tag} \
            ${{ secrets.PUBLISH_USER }}@${{ secrets.PUBLISH_HOST }} ${{ secrets.PUBLISH_PASS }}

    # Run unit tests with release build, similar to the debug build
    unit_tests:
        needs: [build]
        runs-on: ubuntu-latest
        name: Unit Test 
        continue-on-error: True
        outputs:
            status: ${{job.status}}        
        strategy:
          matrix:
            test_dir:
            - coupling
            - fem
            - fields
            - flow
            - input
            - intersection
            - la
            - mesh
            - output
            - scripts
            - system
            - test_scripts
            - tools
        steps:  
        - uses: actions/checkout@v3
        - uses: actions/download-artifact@v3
          with:
            name: build_dir
        - run: config/tests/run_with_build_dir.sh make -C build_tree/unit_tests/${{matrix.test_dir}} -k all-test


    # TODO: modify to run integration tests with release image
    #integration_tests:
        #needs: [build]
        #runs-on: ubuntu-latest
        #name: Integration Test ${{matrix.test_dir}}
        #continue-on-error: True
        #outputs:
            #status: ${{job.status}}
        #strategy:
          #matrix:
            #test_dir:
            #- 01_cmd_line
            #- 02_generic_input
            #- 03_generic_output
            #- 04_generic_mesh
            #- 05_tutorial
            #- 06_errors
            #- 10_darcy
            #- 11_darcy_bc
            #- 12_darcy_frac
            #- 13_darcy_time
            #- 14_darcy_richards
            #- 20_solute_fv
            #- 21_solute_fv_frac
            #- 22_solute_fv_time
            #- 24_solute_dg
            #- 25_solute_dg_bc
            #- 26_solute_dg_frac
            #- 27_solute_dg_time
            #- 30_sorption
            #- 31_dual_por
            #- 32_decay
            #- 33_reaction
            #- 34_sorption_dg
            #- 40_heat
            #- 50_mechanics
            
        #steps:  
        #- uses: actions/checkout@v3
        #- uses: actions/download-artifact@v3
          #with:
            #name: build_dir
        #- run: config/tests/run_with_build_dir.sh tests/runtest tests/${{matrix.test_dir}}  --keep-going --batch 
        #- name: Report
          #run: |
            #echo "Job result: ${{job.result}}"
            #echo "Job status: ${{job.status}}"
